### ISSUE TITLE
Inspections do not show up in IntellliJ

### ISSUE THREAD

**Issue by beatrichartz** [chrisly42/cajon-plugin#1]
Hi, this looks like a great plugin. When I install it on latest Intellij Ultimate with a project in kotlin 1.3.72 and assertJ 3.13.2, inspections do not show up though, even if I copy the lines in the README. Am I doing something wrong?

**Comment by chrisly42** [comment]
Hi there. Your project is a Kotlin language project, right? The plugin currently only works with Java language projects (there're a couple of reasons behind this, and they way IntelliJ supports PSI/AST-Analysis for other languages is pretty uhm... limited).

There was hardly any feedback on the plugin since its release, and there doesn't seem to be much interest in a Kotlin version (which would have been called Kajon ;) ). So there is no Kotlin-support, though the plugin itself was written in Kotlin.

**Comment by beatrichartz** [comment]
Oh I see. I for one would be very interested then in Kajon!

**Comment by mmalicki** [comment]
Hi, I've had the same issue, couldn't figure it out why inspections don't show up. I assumed that it worked for kotlin too, since it has quite a lot of kotlin code itself ;) 

Maybe some note would be worth adding so other people don't have the same issue.

**Comment by chrisly42** [comment]
I will add a note about it to the documentation. Sorry for the inconvenience.

**Comment by ianbrandt** [comment]
+1 for Kajon.
